# Site settings
title: SpookySec
description: "root@SpookySec:~#"
baseurl: "/" # for test: remove string '/space-jekyll-template' to ''
url: "https://blog.spookysec.net/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: Spooks
user_title: Spooks
email: ronnie@spookysec.net
twitter_username: NaisuBanana
github_username:  Sq00ky
linkedin_public_url: rBartwitz # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
profile_picture: https://avatars2.githubusercontent.com/u/44957111?s=460&u=ae50f9e5e53e1b2402d7702abdef2d0492cb8958&v=4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: tags
      url: /tags
      key_trigger: 3

# projects in header index
projects:
  - name: Session Spoofing
    url: https://github.com/Sq00ky/SMB-Session-Spoofing
  - name: LeetLinked
    url: https://github.com/Sq00ky/LeetLinked
  - name: Clipboard Data Stealer
    url: https://github.com/Sq00ky/Clipboard-Data-Stealer
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
